### ISSUE TITLE
Future plans to add a minimal install option

### ISSUE THREAD

**Issue by mikeroyal** [lubuntu-team/calamares-settings-ubuntu#2]
Hi guys, I was wondering if there were any plans to add a minimal install option like there is in the Ubiquity installer?
![min-install](https://user-images.githubusercontent.com/45159366/57009138-aa297700-6ba9-11e9-9b93-47cee8f24c67.jpeg)

**Comment by wxl** [comment]
[yep](https://phab.lubuntu.me/T58)

**Comment by candrapersada** [comment]
support minimal install for other ubuntu?

**Comment by wxl** [comment]
@candrapersada see #5 tl;dr no other Ubuntu is currently using Calamares.
