### ISSUE TITLE
Slideshow not showing

### ISSUE THREAD

**Issue by ubuntucinnamonremix** [lubuntu-team/calamares-settings-ubuntu#3]
As of testing of Calamares-settings-cinnamon-remix:

The installing slideshow didn’t show. After running it in terminal, the following plugin is required to do this as when it was installed the issue was fixed:

QtQuick 2.0

The packages needed are qml-module-qtquick-dialogs, qml-module-qtquick-controls, qml-module-qtquick-layouts, and qml-module-qtquick-window2. This should fix this issue. Make a dependency.

**Comment by tsimonq2** [comment]
Further discussion of this [is on Phabricator](https://phab.lubuntu.me/T134).
