### ISSUE TITLE
calamares support for ubuntu and other ubuntu flavours?

### ISSUE THREAD

**Issue by candrapersada** [lubuntu-team/calamares-settings-ubuntu#5]
calamares support for other ubuntu?

**Comment by wxl** [comment]
If you're asking if other flavors use Calamares, not yet. Kubuntu has been considering it, but hasn't taken the leap, despite KDE Neon using it. Any of them *could* use it, but they don't. 

On the other hand, if you're from a downstream derivative of Ubuntu (e.g. Mint), you could create your own package modeled after this one using the instructions in the README. If you need further help, I would actually suggest checking with [Calamares](https://github.com/calamares) itself.
